# New secrets generated by Terraform
resource "aws_secretsmanager_secret" "terraform_generated" {
  name = "terraform-secrets-${random_string.suffix.result}"
  recovery_window_in_days = 7
  
  description = "Secrets generated by Terraform (manual + generated)"
}

resource "random_string" "suffix" {
  length  = 4
  special = false
  upper   = false
}


# Create random password for DB
resource "random_password" "db_password" {
  length           = 18
  special          = false
}

# Secrets Manager
resource "aws_secretsmanager_secret_version" "terraform_generated" {
  secret_id     = aws_secretsmanager_secret.terraform_generated.id
  secret_string = jsonencode(merge(
    jsondecode(data.aws_secretsmanager_secret_version.manual.secret_string),
    {
      # RDS credentials
      db_username = var.db_username
      db_password = random_password.db_password.result
      db_host     = aws_db_instance.main.address
      db_port     = aws_db_instance.main.port
      db_name     = var.db_name
      DATABASE_URL      = "postgresql://${aws_db_instance.main.username}:${random_password.db_password.result}@${aws_db_instance.main.endpoint}/${aws_db_instance.main.db_name}"

      REDIS_URL        = "redis://${aws_elasticache_replication_group.valkey.primary_endpoint_address}:6379/1"
      
      # API / CORS
      CORS_ALLOWED_ORIGINS   = "https://${aws_cloudfront_distribution.main.domain_name}"
      CSRF_TRUSTED_ORIGINS   = "https://${aws_cloudfront_distribution.main.domain_name}"
      FRONTEND_URL           = "https://${aws_cloudfront_distribution.main.domain_name}"
      ALLEGRO_REDIRECT_URI   = "https://${aws_cloudfront_distribution.main.domain_name}/api/allegro/callback/"
      REACT_APP_API_BASE_URL = "https://${aws_cloudfront_distribution.main.domain_name}"
    }
  ))
}
